# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.heading = QtWidgets.QLabel(Form)
        self.heading.setStyleSheet("\n"
"color: rgb(238, 238, 236);\n"
"font: 85 36pt \"FreeSans\";\n"
"margin-bottom: 32px;")
        self.heading.setObjectName("heading")
        self.verticalLayout.addWidget(self.heading, 0, QtCore.Qt.AlignHCenter)
        self.password = QtWidgets.QLabel(Form)
        self.password.setStyleSheet("\n"
"color: rgb(238, 238, 236);\n"
"font: 85 16pt \"FreeSans\";\n"
"")
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 32)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input1 = QtWidgets.QLineEdit(Form)
        self.input1.setAutoFillBackground(False)
        self.input1.setStyleSheet("background-color: rgb(52, 49, 49);\n"
"color: rgb(238, 238, 236);\n"
"font: 85 16pt \"FreeSans\";\n"
"padding: 8px;\n"
"margin: 16px;")
        self.input1.setObjectName("input1")
        self.horizontalLayout_2.addWidget(self.input1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"color: rgb(238, 238, 236);\n"
"font: 85 20pt \"FreeSans\";\n"
"padding: 8px;\n"
"margin: 16px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.password2 = QtWidgets.QLabel(Form)
        self.password2.setStyleSheet("color: rgb(238, 238, 236);\n"
"font: 85 16pt \"FreeSans\";")
        self.password2.setObjectName("password2")
        self.verticalLayout.addWidget(self.password2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input2 = QtWidgets.QLineEdit(Form)
        self.input2.setStyleSheet("background-color: rgb(52, 49, 49);\n"
"color: rgb(238, 238, 236);\n"
"font: 85 16pt \"FreeSans\";\n"
"padding: 8px;\n"
"margin: 16px;")
        self.input2.setClearButtonEnabled(False)
        self.input2.setObjectName("input2")
        self.horizontalLayout_3.addWidget(self.input2)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"color: rgb(238, 238, 236);\n"
"font: 85 20pt \"FreeSans\";\n"
"padding: 8px;\n"
"margin: 16px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 32, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"color: rgb(238, 238, 236);\n"
"font: 85 28pt \"FreeSans\";\n"
"padding: 32px;\n"
"margin: 16px;")
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.login_btn = QtWidgets.QPushButton(Form)
        self.login_btn.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"color: rgb(238, 238, 236);\n"
"font: 85 28pt \"FreeSans\";\n"
"padding: 32px;\n"
"margin: 16px;")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout.addWidget(self.login_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.heading.setText(_translate("Form", "Password Manager"))
        self.password.setText(_translate("Form", "New Password : "))
        self.input1.setPlaceholderText(_translate("Form", "password here"))
        self.pushButton.setText(_translate("Form", "View"))
        self.password2.setText(_translate("Form", "Confirm Password :"))
        self.input2.setPlaceholderText(_translate("Form", "password here"))
        self.pushButton_2.setText(_translate("Form", "View"))
        self.exit_btn.setText(_translate("Form", "Exit"))
        self.login_btn.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
