# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 750)
        Form.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 32, -1, 16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(1, 135, 134);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        self.quit_button = QtWidgets.QPushButton(Form)
        self.quit_button.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(176, 0, 32);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.quit_button.setObjectName("quit_button")
        self.horizontalLayout.addWidget(self.quit_button)
        self.add_new_button = QtWidgets.QPushButton(Form)
        self.add_new_button.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.add_new_button.setObjectName("add_new_button")
        self.horizontalLayout.addWidget(self.add_new_button)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.filter_lineEdit = QtWidgets.QLineEdit(Form)
        self.filter_lineEdit.setMinimumSize(QtCore.QSize(0, 48))
        self.filter_lineEdit.setStyleSheet("background-color: rgb(46, 45, 45);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 16pt \"FreeSans\";\n"
"margin: 16px;\n"
"padding: 8px;")
        self.filter_lineEdit.setObjectName("filter_lineEdit")
        self.gridLayout.addWidget(self.filter_lineEdit, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("QScrollBar::vertical {              \n"
"        border: 1px solid #999999;\n"
"        background:rgb(211, 215, 207);\n"
"        width: 24px;    \n"
"        margin: 24px 0px 24px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        min-height: 24px;\n"
"         background: rgb(136, 138, 133);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"        height: 24px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"        height: 24px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 964, 694))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # self.verticalLayout = QtWidgets.QVBoxLayout()
        # self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;\n"
"text-align: left;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setStyleSheet("font: 100 16pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setStyleSheet("font: 100 16pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        # self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 16)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 16)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_12.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_5.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 16)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_16.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_6.addWidget(self.pushButton_16)
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_6.addWidget(self.pushButton_15)
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_6.addWidget(self.pushButton_13)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 16)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_18.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_7.addWidget(self.pushButton_18)
        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_7.addWidget(self.pushButton_17)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_7.addWidget(self.pushButton_14)
        self.horizontalLayout_7.setStretch(0, 5)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_21.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_8.addWidget(self.pushButton_21)
        self.pushButton_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_8.addWidget(self.pushButton_20)
        self.pushButton_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_8.addWidget(self.pushButton_19)
        self.horizontalLayout_8.setStretch(0, 5)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 16)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_24.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_9.addWidget(self.pushButton_24)
        self.pushButton_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_9.addWidget(self.pushButton_23)
        self.pushButton_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_9.addWidget(self.pushButton_22)
        self.horizontalLayout_9.setStretch(0, 5)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.back_button.setText(_translate("Form", "Back"))
        self.quit_button.setText(_translate("Form", "Quit"))
        self.add_new_button.setText(_translate("Form", "Add New"))
        self.filter_lineEdit.setPlaceholderText(_translate("Form", "Filter"))
        self.pushButton.setText(_translate("Form", "1. Pass"))
        self.pushButton_2.setText(_translate("Form", "C_user"))
        self.pushButton_3.setText(_translate("Form", "C_pass"))
        self.pushButton_4.setText(_translate("Form", "PushButton"))
        self.pushButton_5.setText(_translate("Form", "PushButton"))
        self.pushButton_6.setText(_translate("Form", "PushButton"))
        self.pushButton_9.setText(_translate("Form", "PushButton"))
        self.pushButton_8.setText(_translate("Form", "PushButton"))
        self.pushButton_7.setText(_translate("Form", "PushButton"))
        self.pushButton_12.setText(_translate("Form", "PushButton"))
        self.pushButton_11.setText(_translate("Form", "PushButton"))
        self.pushButton_10.setText(_translate("Form", "PushButton"))
        self.pushButton_16.setText(_translate("Form", "PushButton"))
        self.pushButton_15.setText(_translate("Form", "PushButton"))
        self.pushButton_13.setText(_translate("Form", "PushButton"))
        self.pushButton_18.setText(_translate("Form", "PushButton"))
        self.pushButton_17.setText(_translate("Form", "PushButton"))
        self.pushButton_14.setText(_translate("Form", "PushButton"))
        self.pushButton_21.setText(_translate("Form", "PushButton"))
        self.pushButton_20.setText(_translate("Form", "PushButton"))
        self.pushButton_19.setText(_translate("Form", "PushButton"))
        self.pushButton_24.setText(_translate("Form", "PushButton"))
        self.pushButton_23.setText(_translate("Form", "PushButton"))
        self.pushButton_22.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
