# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(Form)
        self.username_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label, 0, QtCore.Qt.AlignVCenter)
        self.username_lineEdit = QtWidgets.QLineEdit(Form)
        self.username_lineEdit.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.horizontalLayout.addWidget(self.username_lineEdit)
        self.username_copy_button = QtWidgets.QPushButton(Form)
        self.username_copy_button.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.username_copy_button.setObjectName("username_copy_button")
        self.horizontalLayout.addWidget(self.username_copy_button, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_2.addWidget(self.password_label, 0, QtCore.Qt.AlignVCenter)
        self.password_lineEdit = QtWidgets.QLineEdit(Form)
        self.password_lineEdit.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.horizontalLayout_2.addWidget(self.password_lineEdit)
        self.password_view_button = QtWidgets.QPushButton(Form)
        self.password_view_button.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.password_view_button.setObjectName("password_view_button")
        self.horizontalLayout_2.addWidget(self.password_view_button)
        self.password_copy_button = QtWidgets.QPushButton(Form)
        self.password_copy_button.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.password_copy_button.setObjectName("password_copy_button")
        self.horizontalLayout_2.addWidget(self.password_copy_button)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 11)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.url_label = QtWidgets.QLabel(Form)
        self.url_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.url_label.setObjectName("url_label")
        self.horizontalLayout_3.addWidget(self.url_label)
        self.url_lineEdit = QtWidgets.QLineEdit(Form)
        self.url_lineEdit.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.horizontalLayout_3.addWidget(self.url_lineEdit)
        self.url_copy_button = QtWidgets.QPushButton(Form)
        self.url_copy_button.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.url_copy_button.setObjectName("url_copy_button")
        self.horizontalLayout_3.addWidget(self.url_copy_button)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 11)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.caption_label = QtWidgets.QLabel(Form)
        self.caption_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.caption_label.setObjectName("caption_label")
        self.horizontalLayout_4.addWidget(self.caption_label)
        self.caption_lineEdit = QtWidgets.QLineEdit(Form)
        self.caption_lineEdit.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.caption_lineEdit.setObjectName("caption_lineEdit")
        self.horizontalLayout_4.addWidget(self.caption_lineEdit)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tags_label = QtWidgets.QLabel(Form)
        self.tags_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.tags_label.setObjectName("tags_label")
        self.horizontalLayout_5.addWidget(self.tags_label)
        self.tags_lineEdit = QtWidgets.QLineEdit(Form)
        self.tags_lineEdit.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.tags_lineEdit.setObjectName("tags_lineEdit")
        self.horizontalLayout_5.addWidget(self.tags_lineEdit)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.history_label = QtWidgets.QLabel(Form)
        self.history_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.history_label.setObjectName("history_label")
        self.horizontalLayout_6.addWidget(self.history_label)
        self.history_textBrowser = QtWidgets.QTextBrowser(Form)
        self.history_textBrowser.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"font: 63 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);")
        self.history_textBrowser.setObjectName("history_textBrowser")
        self.horizontalLayout_6.addWidget(self.history_textBrowser)
        
        self.history_view_button = QtWidgets.QPushButton(Form)
        self.history_view_button.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.history_view_button.setObjectName("history_view_button")
        self.horizontalLayout_6.addWidget(self.history_view_button)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 7)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setStyleSheet("background-color: rgb(1, 135, 134);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_7.addWidget(self.back_button)
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setStyleSheet("background-color: rgb(176, 0, 32);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_7.addWidget(self.delete_button)
        self.ok_button = QtWidgets.QPushButton(Form)
        self.ok_button.setStyleSheet("background-color: rgb(55, 0, 179);\n"
"font: 81 16pt \"FreeSans\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px;\n"
"margin: 8px;")
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_7.addWidget(self.ok_button)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 3)
        self.verticalLayout.setStretch(6, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username_label.setText(_translate("Form", "Username :"))
        self.username_lineEdit.setPlaceholderText(_translate("Form", "username"))
        self.username_copy_button.setText(_translate("Form", "Copy"))
        self.password_label.setText(_translate("Form", "Password :"))
        self.password_lineEdit.setPlaceholderText(_translate("Form", "password"))
        self.password_view_button.setText(_translate("Form", "View"))
        self.password_copy_button.setText(_translate("Form", "Copy"))
        self.url_label.setText(_translate("Form", "URL :"))
        self.url_lineEdit.setPlaceholderText(_translate("Form", "Website Url"))
        self.url_copy_button.setText(_translate("Form", "Copy"))
        self.caption_label.setText(_translate("Form", "Caption :"))
        self.caption_lineEdit.setPlaceholderText(_translate("Form", "Caption"))
        self.tags_label.setText(_translate("Form", "Tags :"))
        self.tags_lineEdit.setPlaceholderText(_translate("Form", "comma seperated tags"))
        self.history_label.setText(_translate("Form", "History :"))
        self.history_textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'FreeSans\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; -qt-user-state:131073;\"><br /></p></body></html>"))
        self.history_textBrowser.setPlaceholderText(_translate("Form", "your password history will appear here"))
        self.history_view_button.setText(_translate("Form", "View"))
        self.back_button.setText(_translate("Form", "Back"))
        self.delete_button.setText(_translate("Form", "Delete"))
        self.ok_button.setText(_translate("Form", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
