# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftpServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 753)
        Form.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.default_button = QtWidgets.QPushButton(self.page)
        self.default_button.setStyleSheet("font: 81 24pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.default_button.setObjectName("default_button")
        self.horizontalLayout.addWidget(self.default_button)
        self.select_button = QtWidgets.QPushButton(self.page)
        self.select_button.setStyleSheet("font: 81 24pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.select_button.setObjectName("select_button")
        self.horizontalLayout.addWidget(self.select_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ip_label = QtWidgets.QLabel(self.page_2)
        self.ip_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ip_label.setObjectName("ip_label")
        self.horizontalLayout_2.addWidget(self.ip_label, 0, QtCore.Qt.AlignLeft)
        self.ip_colon_label = QtWidgets.QLabel(self.page_2)
        self.ip_colon_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ip_colon_label.setObjectName("ip_colon_label")
        self.horizontalLayout_2.addWidget(self.ip_colon_label)
        self.ip_value_label = QtWidgets.QLabel(self.page_2)
        self.ip_value_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ip_value_label.setObjectName("ip_value_label")
        self.horizontalLayout_2.addWidget(self.ip_value_label)
        self.ip_copy_button = QtWidgets.QPushButton(self.page_2)
        self.ip_copy_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px 32px 8px 32px;")
        self.ip_copy_button.setObjectName("ip_copy_button")
        self.horizontalLayout_2.addWidget(self.ip_copy_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 5)
        self.horizontalLayout_2.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.port_label = QtWidgets.QLabel(self.page_2)
        self.port_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.port_label.setObjectName("port_label")
        self.horizontalLayout_3.addWidget(self.port_label, 0, QtCore.Qt.AlignLeft)
        self.port_colon_label = QtWidgets.QLabel(self.page_2)
        self.port_colon_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.port_colon_label.setObjectName("port_colon_label")
        self.horizontalLayout_3.addWidget(self.port_colon_label)
        self.port_value_label = QtWidgets.QLabel(self.page_2)
        self.port_value_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.port_value_label.setObjectName("port_value_label")
        self.horizontalLayout_3.addWidget(self.port_value_label)
        self.port_copy_button = QtWidgets.QPushButton(self.page_2)
        self.port_copy_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px 32px 8px 32px;")
        self.port_copy_button.setObjectName("port_copy_button")
        self.horizontalLayout_3.addWidget(self.port_copy_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 5)
        self.horizontalLayout_3.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ip_port_label = QtWidgets.QLabel(self.page_2)
        self.ip_port_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ip_port_label.setObjectName("ip_port_label")
        self.horizontalLayout_4.addWidget(self.ip_port_label, 0, QtCore.Qt.AlignLeft)
        self.ip_port_colon_label = QtWidgets.QLabel(self.page_2)
        self.ip_port_colon_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ip_port_colon_label.setObjectName("ip_port_colon_label")
        self.horizontalLayout_4.addWidget(self.ip_port_colon_label)
        self.ip_port_value_label = QtWidgets.QLabel(self.page_2)
        self.ip_port_value_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ip_port_value_label.setObjectName("ip_port_value_label")
        self.horizontalLayout_4.addWidget(self.ip_port_value_label)
        self.ip_port_copy_button = QtWidgets.QPushButton(self.page_2)
        self.ip_port_copy_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px 32px 8px 32px;")
        self.ip_port_copy_button.setObjectName("ip_port_copy_button")
        self.horizontalLayout_4.addWidget(self.ip_port_copy_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 5)
        self.horizontalLayout_4.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.username_label = QtWidgets.QLabel(self.page_2)
        self.username_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.username_label.setObjectName("username_label")
        self.horizontalLayout_5.addWidget(self.username_label, 0, QtCore.Qt.AlignLeft)
        self.username_colon_label = QtWidgets.QLabel(self.page_2)
        self.username_colon_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.username_colon_label.setObjectName("username_colon_label")
        self.horizontalLayout_5.addWidget(self.username_colon_label)
        self.username_value_label = QtWidgets.QLabel(self.page_2)
        self.username_value_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.username_value_label.setObjectName("username_value_label")
        self.horizontalLayout_5.addWidget(self.username_value_label)
        self.username_copy_button = QtWidgets.QPushButton(self.page_2)
        self.username_copy_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px 32px 8px 32px;")
        self.username_copy_button.setObjectName("username_copy_button")
        self.horizontalLayout_5.addWidget(self.username_copy_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 5)
        self.horizontalLayout_5.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.password_label = QtWidgets.QLabel(self.page_2)
        self.password_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_6.addWidget(self.password_label, 0, QtCore.Qt.AlignLeft)
        self.password_colon_label = QtWidgets.QLabel(self.page_2)
        self.password_colon_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.password_colon_label.setObjectName("password_colon_label")
        self.horizontalLayout_6.addWidget(self.password_colon_label)
        self.password_value_label = QtWidgets.QLabel(self.page_2)
        self.password_value_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.password_value_label.setObjectName("password_value_label")
        self.horizontalLayout_6.addWidget(self.password_value_label)
        self.password_copy_button = QtWidgets.QPushButton(self.page_2)
        self.password_copy_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px 32px 8px 32px;")
        self.password_copy_button.setObjectName("password_copy_button")
        self.horizontalLayout_6.addWidget(self.password_copy_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(2, 5)
        self.horizontalLayout_6.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.folder_shared_label = QtWidgets.QLabel(self.page_2)
        self.folder_shared_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.folder_shared_label.setObjectName("folder_shared_label")
        self.horizontalLayout_7.addWidget(self.folder_shared_label, 0, QtCore.Qt.AlignLeft)
        self.folder_shared_colon_label = QtWidgets.QLabel(self.page_2)
        self.folder_shared_colon_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.folder_shared_colon_label.setObjectName("folder_shared_colon_label")
        self.horizontalLayout_7.addWidget(self.folder_shared_colon_label)
        self.folder_shared_value_text_browser = QtWidgets.QTextBrowser(self.page_2)
        self.folder_shared_value_text_browser.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.folder_shared_value_text_browser.setObjectName("folder_shared_value_text_browser")
        self.horizontalLayout_7.addWidget(self.folder_shared_value_text_browser)
        self.folder_shared_copy_button = QtWidgets.QPushButton(self.page_2)
        self.folder_shared_copy_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px 32px 8px 32px;")
        self.folder_shared_copy_button.setObjectName("folder_shared_copy_button")
        self.horizontalLayout_7.addWidget(self.folder_shared_copy_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_7.setStretch(0, 5)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 5)
        self.horizontalLayout_7.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.anonymous_label = QtWidgets.QLabel(self.page_2)
        self.anonymous_label.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.anonymous_label.setObjectName("anonymous_label")
        self.horizontalLayout_8.addWidget(self.anonymous_label, 0, QtCore.Qt.AlignLeft)
        self.anonymous_enable_button = QtWidgets.QPushButton(self.page_2)
        self.anonymous_enable_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"padding: 8px 32px 8px 32px;")
        self.anonymous_enable_button.setObjectName("anonymous_enable_button")
        self.horizontalLayout_8.addWidget(self.anonymous_enable_button)
        self.horizontalLayout_8.setStretch(0, 5)
        self.horizontalLayout_8.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.log_text_browser = QtWidgets.QTextBrowser(self.page_2)
        self.log_text_browser.setStyleSheet("font: 81 16pt \"FreeSans\";\n"
"background-color: rgb(46, 45, 45);\n"
"color: rgb(255, 255, 255);")
        self.log_text_browser.setObjectName("log_text_browser")
        self.verticalLayout.addWidget(self.log_text_browser)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.quit_button = QtWidgets.QPushButton(self.page_2)
        self.quit_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(176, 0, 32);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.quit_button.setObjectName("quit_button")
        self.horizontalLayout_9.addWidget(self.quit_button)
        self.start_button = QtWidgets.QPushButton(self.page_2)
        self.start_button.setStyleSheet("font: 81 20pt \"FreeSans\";\n"
"background-color: rgb(55, 0, 179);\n"
"color: rgb(255, 255, 255);\n"
"padding: 16px;")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_9.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 6)
        self.verticalLayout.setStretch(8, 2)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.default_button.setText(_translate("Form", "Default"))
        self.select_button.setText(_translate("Form", "Select"))
        self.ip_label.setText(_translate("Form", "IP"))
        self.ip_colon_label.setText(_translate("Form", ":"))
        self.ip_value_label.setText(_translate("Form", "192.168.2.1"))
        self.ip_copy_button.setText(_translate("Form", "Copy"))
        self.port_label.setText(_translate("Form", "PORT"))
        self.port_colon_label.setText(_translate("Form", ":"))
        self.port_value_label.setText(_translate("Form", "5000"))
        self.port_copy_button.setText(_translate("Form", "Copy"))
        self.ip_port_label.setText(_translate("Form", "IP with PORT"))
        self.ip_port_colon_label.setText(_translate("Form", ":"))
        self.ip_port_value_label.setText(_translate("Form", "192.168.2.1:5000"))
        self.ip_port_copy_button.setText(_translate("Form", "Copy"))
        self.username_label.setText(_translate("Form", "Username"))
        self.username_colon_label.setText(_translate("Form", ":"))
        self.username_value_label.setText(_translate("Form", "jarvisuser"))
        self.username_copy_button.setText(_translate("Form", "Copy"))
        self.password_label.setText(_translate("Form", "Password"))
        self.password_colon_label.setText(_translate("Form", ":"))
        self.password_value_label.setText(_translate("Form", "123456"))
        self.password_copy_button.setText(_translate("Form", "Copy"))
        self.folder_shared_label.setText(_translate("Form", "Folder Shared"))
        self.folder_shared_colon_label.setText(_translate("Form", ":"))
        self.folder_shared_value_text_browser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'FreeSans\'; font-size:20pt; font-weight:80; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/home/user/temp1/temp2/temp3/temp4/temp5/temp6/random-folder-shared</p></body></html>"))
        self.folder_shared_copy_button.setText(_translate("Form", "Copy"))
        self.anonymous_label.setText(_translate("Form", "Anonymous Access"))
        self.anonymous_enable_button.setText(_translate("Form", "Enable"))
        self.log_text_browser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'FreeSans\'; font-size:16pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Serving FTP on 127.0.0.1:21</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[]127.0.0.1:2503 connected.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 220 Ready.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 &lt;== USER anonymous</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 331 Username ok, send password.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 &lt;== PASS ******</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 230 Login successful.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[anonymous]@127.0.0.1:2503 User anonymous logged in.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 &lt;== TYPE A</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 200 Type set to: ASCII.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 &lt;== PASV</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 227 Entering passive mode (127,0,0,1,9,201).</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 &lt;== LIST</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 150 File status okay. About to open data connection.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[anonymous]@127.0.0.1:2503 OK LIST &quot;/&quot;. Transfer starting.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 226 Transfer complete.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[anonymous]@127.0.0.1:2503 Transfer complete. 706 bytes transmitted.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 &lt;== QUIT</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2503 ==&gt; 221 Goodbye.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[anonymous]@127.0.0.1:2503 Disconnected.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.quit_button.setText(_translate("Form", "Quit"))
        self.start_button.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
